version: '2'
services:
    peluqueria-mysql:
        container_name: peluqueria-mysql
        image: mysql:5.7.13
        # volumes:
        #     - ~/volumes/jhipster/peluqueria/mysql/:/var/lib/mysql/
        environment:
            - MYSQL_USER=root
            - MYSQL_ALLOW_EMPTY_PASSWORD=yes
            - MYSQL_DATABASE=peluqueria
        ports:
            - 3306:3306
        command: mysqld --lower_case_table_names=1 --skip-ssl
